Args = --add-exports=java.base/jdk.internal.misc=org.graalvm.nativeimage.guest \
       --add-exports=org.graalvm.nativeimage.base/com.oracle.svm.sdk.staging.hosted.layeredimage=ALL-UNNAMED \
       --add-exports=org.graalvm.nativeimage.base/com.oracle.svm.sdk.staging.layeredimage=ALL-UNNAMED
