Args = -H:+UnlockExperimentalVMOptions \
       --add-exports=org.graalvm.nativeimage.base/com.oracle.svm.sdk.staging.hosted.layeredimage=ALL-UNNAMED \
       --add-exports=org.graalvm.nativeimage.base/com.oracle.svm.sdk.staging.layeredimage=ALL-UNNAMED \
       -H:Features=example.spring.baselayer.ReflectArrayInitialLayerFeature \
       -H:LayerCreate=@layer-create.args \
       -H:+RelativeCodePointers \
       -H:-UnlockExperimentalVMOptions
